# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/FlyToday
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "src/requirements.txt" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r src/requirements.txt
      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "src/requirements.txt" }}
      - persist_to_workspace:
          root: ~/FlyToday
          paths:
            - ./
  test:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/FlyToday
    steps:
      - attach_workspace:
          at: ~/FlyToday
      - run:
          name: Run unit tests
          command: |
            . env/bin/activate
            make test
  lint:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/FlyToday
    steps:
      - attach_workspace:
          at: ~/FlyToday
      - run:
          name: Check pycodestyle
          command: |
            . env/bin/activate
            make lint
workflows:
  version: 2
  build-test-lint:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
